services:
  pgdatabase:  
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi

    ports:
      - "5432:5432"
    
    volumes:
      - "ny_taxi_postges_data:/var/lib/postgresql"

    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    networks:
      - pg-network

  ingest_data:
    # image: taxi_ingest:v001
    build: .
    depends_on:
      - pgdatabase
    environment:
      # - pg_host=pgdatabase
      - pg_user=root
      - pg_pass=root
      - pg_port=5432
      - pg_db=ny_taxi
      - target_table=yelow_taxi_trips_2021_1
      - year=2021
      - month=1
      - chunksize=100000
    command: >
      --pg-host pgdatabase
    networks:
      - pg-network

# for presistance storage
volumes:
  ny_taxi_postges_data:
  pgadmin_data:

networks:
  pg-network: