services:
  pgdatabase:
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=pgdatabase
      - POSTGRES_DB=taxi_zone_lookup
    # volumes:
    #   - "taxi_zone_lookup_data:/var/lib/postgresql"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # volumes:
    #   - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

  get_data:
    depends_on:
      - pgdatabase
    build: .
    environment:
      - PG_USER=root
      - PG_PASS=root
      - PG_HOST=pgdatabase
      - PG_PORT=5432
      - TARGET_TABLE=taxi_zone

# uncomment below as well as above lines for persistent storage
# volumes:
#   taxi_zone_lookup_data:
#   pgadmin_data:
