services:
  pgdatabase:
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=pgdatabase
      - POSTGRES_DB=ny_taxi
    volumes:
      - "ny_taxi_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - pg-net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - pg-net      
  get_data:
    depends_on:
      - pgdatabase
    build: .
    environment:
      - PG_USER=root
      - PG_PASS=root
      - PG_HOST=pgdatabase
      - PG_PORT=5432
      - TARGET_TABLE=zones
    networks:
      - pg-net

volumes:
  ny_taxi_data:
  pgadmin_data:

networks:
  pg-net:
